// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/demo/scrollIntoView":{"path":"demo/scrollintoview","id":"docs/demo/scrollIntoView","parentId":"DocLayout"},"docs/demo/customMask":{"path":"demo/custommask","id":"docs/demo/customMask","parentId":"DocLayout"},"docs/demo/placement":{"path":"demo/placement","id":"docs/demo/placement","parentId":"DocLayout"},"docs/demo/animated":{"path":"demo/animated","id":"docs/demo/animated","parentId":"DocLayout"},"docs/demo/notFound":{"path":"demo/notfound","id":"docs/demo/notFound","parentId":"DocLayout"},"docs/demo/center":{"path":"demo/center","id":"docs/demo/center","parentId":"DocLayout"},"docs/demo/arrow":{"path":"demo/arrow","id":"docs/demo/arrow","parentId":"DocLayout"},"docs/demo/basic":{"path":"demo/basic","id":"docs/demo/basic","parentId":"DocLayout"},"docs/demo/open":{"path":"demo/open","id":"docs/demo/open","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/tangwenhui/kiner/learning/tour/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/tangwenhui/kiner/learning/tour/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/tangwenhui/kiner/learning/tour/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/demo/scrollIntoView': React.lazy(() => import(/* webpackChunkName: "docs__demo__scrollIntoView.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/scrollIntoView.md')),
'docs/demo/customMask': React.lazy(() => import(/* webpackChunkName: "docs__demo__customMask.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/customMask.md')),
'docs/demo/placement': React.lazy(() => import(/* webpackChunkName: "docs__demo__placement.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/placement.md')),
'docs/demo/animated': React.lazy(() => import(/* webpackChunkName: "docs__demo__animated.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/animated.md')),
'docs/demo/notFound': React.lazy(() => import(/* webpackChunkName: "docs__demo__notFound.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/notFound.md')),
'docs/demo/center': React.lazy(() => import(/* webpackChunkName: "docs__demo__center.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/center.md')),
'docs/demo/arrow': React.lazy(() => import(/* webpackChunkName: "docs__demo__arrow.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/arrow.md')),
'docs/demo/basic': React.lazy(() => import(/* webpackChunkName: "docs__demo__basic.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/basic.md')),
'docs/demo/open': React.lazy(() => import(/* webpackChunkName: "docs__demo__open.md" */'/Users/tangwenhui/kiner/learning/tour/docs/demo/open.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/tangwenhui/kiner/learning/tour/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/tangwenhui/kiner/learning/tour/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
