// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/jilin/projects/antd/rc-tour/node_modules/_dumi@2.0.18@dumi/dist/client/theme-api/index.js';
