// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jilin/projects/antd/rc-tour/node_modules/_dumi@2.0.18@dumi/theme-default/slots/LangSwitch/index.js';
